# Generated by Django 6.0.5 on 2026-05-24 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_phone', models.CharField(max_length=15)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('ticket_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_orders', to='matches.fixture')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Order',
                'verbose_name_plural': 'Ticket Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
