# Generated by Django 6.0.5 on 2026-05-24 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('competition', models.CharField(choices=[('KPL', 'Kenyan Premier League'), ('FKF_CUP', 'FKF Cup'), ('CAF', 'CAF Confederation Cup'), ('FRIENDLY', 'Friendly')], default='KPL', max_length=20)),
                ('matchday', models.PositiveIntegerField(default=1)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('tickets_available', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fixture',
                'verbose_name_plural': 'Fixtures',
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(choices=[('WIN', 'Win'), ('DRAW', 'Draw'), ('LOSS', 'Loss')], max_length=4)),
                ('scorers', models.TextField(blank=True, help_text="e.g. Ochieng' 12', Mwangi 90+3'")),
                ('match_report', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='matches.fixture')),
            ],
            options={
                'verbose_name': 'Match Result',
                'verbose_name_plural': 'Match Results',
                'ordering': ['-fixture__match_date'],
            },
        ),
    ]
