# squad/serializers.py
from rest_framework import serializers
from .models import Player


class PlayerSerializer(serializers.ModelSerializer):
    # SerializerMethodField — calls get_age() to return computed value
    age              = serializers.SerializerMethodField()

    # get_position_display() is auto-generated by Django for every choice field
    # returns "Goalkeeper" instead of "GK"
    position_display = serializers.CharField(
        source='get_position_display',
        read_only=True,
    )

    # photo is an ImageField — DRF returns the URL not the file path
    # but only if you have MEDIA_URL configured in settings (already done)
    photo            = serializers.ImageField(read_only=True)

    class Meta:
        model  = Player
        fields = (
            'id', 'name', 'squad_number', 'position',
            'position_display', 'nationality', 'age',
            'bio', 'photo', 'appearances', 'goals',
            'assists', 'clean_sheets', 'is_active',
        )

    def get_age(self, obj):
        # obj is the Player instance — call our model property
        return obj.age