# Generated by Django 6.0.5 on 2026-05-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('fan', 'Fan'), ('ticket_officer', 'Ticket Officer'), ('manager', 'Manager'), ('owner', 'Owner')], default='fan', max_length=20),
        ),
    ]
